#!/usr/bin/ash
# Script defines LAN parameters for Router.
# According to the network changes will be reconfigured WEB server, SSH
# and privoxy.

[ br-lan = "$INTERFACE" ] && {
	[ "$(uci get sabai.vpn.proto)" = "pptp" ] && exit 0
	logger -t SABAI.WAN "Network data of $DEVICE will be updated."
	[ 1 = "$(uci get -p /var/state/ network.lan.up)" ] && {
		ip_lan="$(ifconfig -a br-lan | grep -F "inet addr" | awk '{print $2}' | tr -d 'addr:')"
		permit_access="$(ip route | grep -e "/24 dev br-lan" | awk -F: '{print $0}' | awk '{print $1}')"
				
		uci set uhttpd.main.listen_http=$ip_lan':80'
		uci set uhttpd.main.listen_https=$ip_lan':443'
		uci commit uhttpd

		uci set privoxy.privoxy.permit_access=$permit_access
		uci set privoxy.privoxy.listen_address=$ip_lan':8080 127.0.0.1:8080'
		uci commit privoxy

		uci set dropbear.@dropbear[0].Interface='lan'
		uci commit dropbear

		/etc/init.d/uhttpd restart
		/etc/init.d/dropbear restart
		/etc/init.d/privoxy restart
	}
}