#!/usr/bin/ash

[ wan = "$INTERFACE" ] && {
	logger -t SABAI.WAN "Network data of $DEVICE will be updated."
	[ 1 = "$(uci get -p /var/state/ network.wan.up)" ] && {
		ip="$(ifconfig -a eth0 | grep -F "inet addr" | awk '{print $2}' | tr -d 'addr:')"
		gateway="$( route -n | grep eth0 | grep "UG" | awk '{print $2}')"
		mask="$( route -n | grep eth0 | grep "UH" | awk '{print $3}')"
		uci set network.wan.ipaddr=$ip
		uci set network.wan.gateway=$gateway
		uci commit network
		[ $(uci -c /configs get sabai.wan.factory_mac) ] || /www/bin/wan.sh set_mac
		uci -c /configs set sabai.wan.ipaddr=$ip
		uci -c /configs set sabai.wan.gateway=$gateway
		uci -c /configs set sabai.wan.netmask=$mask
		uci -c /configs commit sabai
		uci set uhttpd.main.listen_http=$ip':80'
		uci set uhttpd.main.listen_https=$ip':443'
		uci commit uhttpd
		uci set privoxy.privoxy.listen_address=$ip':8080 127.0.0.1:8080'		
		uci commit privoxy
		#echo "listen-address=$ip"> /etc/dnsmasq.conf
		#echo "bind-interfaces" >> /etc/dnsmasq.conf
		/etc/init.d/uhttpd restart
		/etc/init.d/dropbear restart
		#/etc/init.d/dnsmasq restart
	}
}
