#!/usr/bin/ash

[ wan = "$INTERFACE" ] && {
	logger -t SABAI.WAN "Network data of $DEVICE will be updated."
	[ 1 = "$(uci get -p /var/state/ network.wan.up)" ] && {
		ip="$(ifconfig -a eth0 | grep -F "inet addr" | awk '{print $2}' | tr -d 'addr:')"
		gateway="$( route -n | grep eth0 | grep "UG" | awk '{print $2}')"
		mask="$( route -n | grep eth0 | grep "UH" | awk '{print $3}')"
		macaddr="$(ifconfig eth0 | awk '/HWaddr/ { print $5 }')"
		uci set network.wan.ipaddr=$ip
		uci set network.wan.gateway=$gateway
		uci set network.wan.netmask=$mask
		uci set network.wan.macaddr=$macaddr
		uci commit network
		uci -c /configs set sabai.wan.ipaddr=$ip
		uci -c /configs set sabai.wan.gateway=$gateway
		uci -c /configs set sabai.wan.netmask=$mask
		uci -c /configs set sabai.wan.macaddr=$macaddr
		uci -c /configs commit sabai
	}
}
