#!/bin/sh /etc/rc.common

START=63

start() {
	logger "SABAI WL:> Setting up wireless."
	if [ -z "$(ifconfig | grep wlan0)" ]; then
   		sh /www/bin/wireless_startup.sh
        return 0;
	else
		logger "SABAI WL:> Wireless interfaces are working."
	fi
}

stop() {
	logger "SABAI WL:> Setting down wireless."
	wifi down
}