#!/bin/sh /etc/rc.common

START=25

USE_PROCD=1

accelerator () {
  rm /etc/config/network
  cp /etc/sabai/accelerator/network /etc/config/network
  rm /etc/config/firewall
  cp /etc/sabai/accelerator/firewall /etc/config/firewall
  rm /www/php/menu.php
  cp /etc/sabai/accelerator/menu.php /www/php/menu.php
  rm /etc/config/system
  cp /etc/sabai/accelerator/uhttpd /www/config/uhttpd
  rm /etc/config/system
  cp /etc/sabai/accelerator/system /etc/config/system
  uci set sabai.general.hostname="vpna"
  echo "vpna" > /proc/sys/kernel/hostname
  echo 1 > /proc/sys/net/ipv4/conf/eth0/proxy_arp
  echo "hit accelerator" > /tmp/result
  /etc/init.d/firewall restart
  /etc/init.d/uhttpd restart
}

router () {
        echo "hit router" > /tmp/result
}

start_service() {
        exec 1>/dev/console  ;
        exec 2>/dev/console  ;
        if [ ! -f /etc/sabai/devtype ]; then
    		touch /etc/sabai/devtype
	fi
	if [$toggle eq ""]||[$(cat /etc/sabai/devtype) eq "" ];
		then 
			logger "Device setup as accelerator"
			accelerator 
			echo "accelerator" > /etc/sabai/devtype
	else
		logger "Device setup as router"
		router
		echo "router" > /etc/sabai/devtype
	fi
}
