#!/bin/sh /etc/rc.common

if [ ! -f /etc/sabai/firstboot ]; then
    touch /etc/sabai/firstboot
fi

toggle=$(ifconfig | grep eth1)

accelerator () {
  rm /etc/config/network
  cp /etc/sabai/accelerator/network /etc/config/network
  rm /etc/config/firewall
  cp /etc/sabai/accelerator/firewall /etc/config/firewall
  rm /www/php/menu.php
  cp /etc/sabai/accelerator/menu.php /www/php/menu.php
  rm /etc/config/system
  cp /etc/sabai/accelerator/system /etc/config/system
  uci set sabai.general.hostname="vpna"
  echo "vpna" > /proc/sys/kernel/hostname
  echo 1 > /proc/sys/net/ipv4/conf/eth0/proxy_arp
  echo "hit accelerator" > /tmp/result
}

router () {
        echo "hit router" > /tmp/result
}


if [$toggle eq ""]||[$(cat /etc/sabai/firstboot) eq "" ];
then 
	echo "accelerator"
	accelerator 
	echo "accelerator" > /etc/sabai/firstboot
else if [ ! -f /tmp/foo.txt ]; then
    echo "File not found!"
fi
	echo "router"
	router
	echo "router" > /etc/sabai/firstboot
fi
